spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  datasource:
    url: jdbc:postgresql://localhost:5434/Bank
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver


